config/routes.rb
Rails.application.routes.draw do
  resources :tickets

  root 'tickets#index'

  get "/signout" => "sessions#destroy", :as => :signout
  get "/signin" => "sessions#new", :as => :signin

  get "/session/create" => "sessions#create"

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :users
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :login, :password
  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protect_from_forgery with: :exception

  helper_method :current_user
  before_action :ensure_logged_in

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
    if session.blank? || session[:user_id].blank?
      redirect_to "/signin"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :ensure_logged_in, only: [:new, :create]

  layout 'session'

  def create

    user = User.where(login: params[:login]).where(password: params[:password]).first

    if user.nil?
      redirect_to root_path, notice: 'Usuário ou Senha inválido(s)'
    else
      session[:user_id] = user.id
      redirect_to root_path
    end

  end

  def destroy
    reset_session
    redirect_to signin_path
  end

  def new
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user_id = session[:user_id]

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:status, :title, :description, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicketSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">
          <i class="glyphicon glyphicon-phone-alt" style="font-size: 20px"></i>
        </a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Abrir Ticket", new_ticket_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">

              <%= current_user.login %>

            <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">

              <li><a href="#">Action</a></li>
              <li role="separator" class="divider"></li>

              <li><%= link_to 'Logout', signout_path %></li>

            </ul>
          </li>
        </ul>
      </div>

    </div>
  </nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
<div class='col-md-6 col-md-offset-3'>

  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label 'Título' %><br>
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <div class="field">
      <%= f.label 'Descrição' %><br>
      <%= f.text_area :description, :class => 'form-control'%>
    </div>
    <div class="field">
      <%= f.label :category %><br>
      <%= f.select :category, ['Hardware', 'Software'], {include_blank: true}, :class => 'form-control'%>
    </div>
    <div class="actions">
      <%= f.submit :class=>'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tickets</h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Status</th>
      <th>Title</th>
      <th>Description</th>
      <th>Category</th>
      <th>Solicitante</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.status %></td>
        <td><%= ticket.title %></td>
        <td><%= ticket.description %></td>
        <td><%= ticket.category %></td>
        <td><%= ticket.user_id %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1 class="span7 text-center"> Abrir Ticket</h1>

<%= render 'form' %>

<% link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @ticket.status %>
</p>

<p>
  <strong>Title:</strong>
  <%= @ticket.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ticket.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @ticket.category %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>